//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom;
using System.CodeDom.Compiler;
using Microsoft.CSharp;

namespace NSCdtest {
    
    public class driver {
		const string DEFAULT_NAMESPACE="NSTest";
        [STAThread()]
        public static void Main(string[] args) {
			
			CodeGeneratorOptions opts=new CodeGeneratorOptions();
			generate(new CSharpCodeProvider(),opts);
        }
		
		static void generate(CodeDomProvider cdp,CodeGeneratorOptions opts){
			CodeCompileUnit ccu=new CodeCompileUnit();
			CodeNamespace ns0,ns;
			
		}
    }
}
